### ISSUE TITLE
stellite_quic_server_bin build fails

### ISSUE THREAD

**Issue by gabiz** [line/stellite#27]
```
ubuntu@ip-172-30-0-157:~/stellite$ ./tools/build.py --target-platform linux --target stellite_quic_server_bin --target-type executable build

chromium is already exists: /home/ubuntu/stellite/third_party/chromium_linux
check chromium ...
check chromium tag ...
copy .gclient ...
copy modified_files ...
copy chromium/src/.gn ...
copy stellite files...
Running: ln -s /home/ubuntu/stellite/stellite
generate ninja script ...
Running: /home/ubuntu/stellite/third_party/depot_tools/gn gen /home/ubuntu/stellite/build_linux/src/out_linux
.gclient file in parent directory /home/ubuntu/stellite/build_linux might not be the file you want to use
Done. Made 407 targets from 101 files in 143ms
Running: /home/ubuntu/stellite/third_party/depot_tools/ninja -C /home/ubuntu/stellite/build_linux/src/out_linux stellite_quic_server_bin
ninja: Entering directory `/home/ubuntu/stellite/build_linux/src/out_linux'
[2024/2024] LINK ./stellite_quic_server_bin
FAILED: stellite_quic_server_bin 
../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -pthread -m64 -Wl,-O1 -Wl,--gc-sections -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,--export-dynamic -o "./stellite_quic_server_bin" -Wl,--start-group @"./stellite_quic_server_bin.rsp"  -Wl,--end-group  -ldl -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -latomic -lgconf-2 -lresolv -lgio-2.0 
obj/stellite/stellite/http_fetcher.o:../stellite/fetcher/http_fetcher.cc:function stellite::HttpFetcher::Request(stellite::HttpRequest const&, long, base::WeakPtr<stellite::HttpFetcherTask::Visitor>): error: undefined reference to 'stellite::HttpRequest::HttpRequest(stellite::HttpRequest const&)'
obj/stellite/stellite/http_fetcher_task.o:../stellite/fetcher/http_fetcher_task.cc:function stellite::HttpFetcherTask::Start(stellite::HttpRequest const&, long): error: undefined reference to 'stellite::HttpRequestHeader::ToString[abi:cxx11]() const'
obj/stellite/stellite/http_fetcher.o:../stellite/fetcher/http_fetcher.cc:function base::internal::BindState<void (stellite::HttpFetcher::*)(int, stellite::HttpRequest const&, long, base::WeakPtr<stellite::HttpFetcherTask::Visitor>), base::WeakPtr<stellite::HttpFetcher>, int, stellite::HttpRequest, long, base::WeakPtr<stellite::HttpFetcherTask::Visitor> >::Destroy(base::internal::BindStateBase const*): error: undefined reference to 'stellite::HttpRequest::~HttpRequest()'
obj/stellite/libstellite_quic_server_base.a(proxy_stream.o):../stellite/server/proxy_stream.cc:function net::ProxyStream::SendResponse(): error: undefined reference to 'stellite::HttpRequest::HttpRequest()'
obj/stellite/libstellite_quic_server_base.a(proxy_stream.o):../stellite/server/proxy_stream.cc:function net::ProxyStream::SendResponse(): error: undefined reference to 'stellite::HttpRequestHeader::SetRawHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/stellite/libstellite_quic_server_base.a(proxy_stream.o):../stellite/server/proxy_stream.cc:function net::ProxyStream::SendResponse(): error: undefined reference to 'stellite::HttpRequest::~HttpRequest()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./tools/build.py", line 1614, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/build.py", line 1601, in main
    output_files = build.build()
  File "./tools/build.py", line 1367, in build
    self.build_target(self.target)
  File "./tools/build.py", line 762, in build_target
    self.execute(command)
  File "./tools/build.py", line 586, in execute
    raise Exception('command execution are failed')
Exception: command execution are failed
```

**Comment by freakhill** [comment]
should we close the issue?
