### ISSUE TITLE
android build fail

### ISSUE THREAD

**Issue by HyundongHwang** [line/stellite#58]
The chromium build succeeds, but the Android build fails.
It seems like there are no related files for google_play_services.
The detailed build logs are shown below.
Environment: Ubuntu 14.04.5 LTS

`
hhd2002@hhdubuntu:~/stellite$ ./tools/build.py --target-platform=android --target stellite_http_client build
chromium is already exists: /home/hhd2002/stellite/third_party/chromium_android
check chromium ...
check chromium tag ...
copy .gclient ...
copy modified_files ...
copy chromium/src/.gn ...
copy node_binder files ...
Running: ln -s /home/hhd2002/stellite/node_binder
copy stellite files...
Running: ln -s /home/hhd2002/stellite/stellite
copya stellite build fakefiles ...
Running: ln -s /home/hhd2002/stellite/build_android/src/tools/vim/chromium.ycm_extra_conf.py /home/hhd2002/stellite/.ycm_extra_conf.py
generate ninja script ...
Running: /home/hhd2002/stellite/third_party/depot_tools/gn gen /home/hhd2002/stellite/build_android/src/out_android_armv6/obj
/home/hhd2002/stellite/build_android/.gclient_entries missing, .gclient file in parent directory /home/hhd2002/stellite/build_android might not be the file you want to use.
ERROR at //build/config/android/internal_rules.gni:2483:15: Script returned non-zero exit code.
              exec_script("//build/android/gyp/find.py",
              ^----------
Current dir: /home/hhd2002/stellite/build_android/src/out_android_armv6/obj/
Command: python -- /home/hhd2002/stellite/build_android/src/build/android/gyp/find.py ../../third_party/android_tools/sdk/extras/google/google_play_services/libproject/google-play-services_lib/res
Returned 1.
stderr:

../../third_party/android_tools/sdk/extras/google/google_play_services/libproject/google-play-services_lib/res does not exist

See //build/config/android/rules.gni:704:5: whence it was called.
    process_resources(process_resources_target_name) {
    ^-------------------------------------------------
See //third_party/android_tools/BUILD.gn:112:1: whence it was called.
android_resources("google_play_services_default_resources") {
^------------------------------------------------------------
See //base/BUILD.gn:1092:7: which caused the file to be included.
      "//third_party/android_tools:cpu_features",
      ^-----------------------------------------
Traceback (most recent call last):
  File "./tools/build.py", line 2037, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/build.py", line 2026, in main
    build.build()
  File "./tools/build.py", line 1382, in build
    build.generate_ninja_script(gn_args=gn_context)
  File "./tools/build.py", line 829, in generate_ninja_script
    self.execute(command, cwd=self.buildspace_src_path)
  File "./tools/build.py", line 723, in execute
    raise Exception('command execution are failed')
Exception: command execution are failed

`

**Comment by HyundongHwang** [comment]
After experiencing a little more difficulty, I found out the cause and solved it.
I have not applied it to the build script yet, but I am going to modify PR as time goes on.

Some files deployed with "google_play_services r28" during the build process of chromium are needed for the build process, but these files did not exist and an error occurred.
You can do the regacy file download, decompress it, put it in the third-party path, and rebuild it as shown below.

`
wget https://dl-ssl.google.com/android/repository/google_play_services_8298000_r28.zip
unzip https://dl-ssl.google.com/android/repository/google_play_services_8298000_r28.zip -d temp
cd temp
cp -rf libproject/google-play-services_lib "build_android/src/third_party/android_tools/sdk/extras/google/google_play_services/libproject/google-play-services_lib" 
`
