### ISSUE TITLE
BuildError on iOS and How do i get supporting bitcode binary in iOS

### ISSUE THREAD

**Issue by suhchansu** [line/stellite#77]
### Simular issue
[#66 BuildError on IOS 11](https://github.com/line/stellite/issues/66)
[#74 Build using modern Xcode](https://github.com/line/stellite/issues/74)

### chromium bitcode command 
`enable_ios_bitcode` [link](https://chromium.googlesource.com/chromium/src/build/config/+/refs/heads/master/ios/BUILD.gn)

### Question
Hello
I need to build stellite for bitcode in iOS
Could you guild me any solution for bitcode?

And, I tried to build using `stellite > tools > build.py`
but, It failed T T
Please give me some guide

My development environment is `XCode 11, MacOS Catalina`
```
Last login: Thu Oct 17 10:49:32 on ttys000
AL01166682:~ user$ cd /Users/user/Desktop/stellite
AL01166682:stellite user$ ./tools/build.py --target-platform=ios --target stellite_http_client build
Running: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /Users/user/Desktop/stellite/third_party/depot_tools
Cloning into '/Users/user/Desktop/stellite/third_party/depot_tools'...
remote: Sending approximately 27.22 MiB ...
remote: Counting objects: 2, done
remote: Finding sources: 100% (2/2)
remote: Total 35324 (delta 24564), reused 35324 (delta 24564)
Receiving objects: 100% (35324/35324), 27.22 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (24564/24564), done.
Running: /Users/user/Desktop/stellite/third_party/depot_tools/fetch --nohooks chromium
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "name": "src",
    "custom_deps": {},
    "custom_vars": {},
  },
]
'
Running: gclient sync --nohooks
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git /Users/user/Desktop/stellite/third_party/chromium_ios/_gclient_src_OujNcp' in '/Users/user/Desktop/stellite/third_party/chromium_ios'
1>Cloning into '/Users/user/Desktop/stellite/third_party/chromium_ios/_gclient_src_OujNcp'...
1>remote: Sending approximately 17.26 GiB ...
1>remote: Counting objects: 224736, done
1>remote: Finding sources: 100% (392/392)
1>error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
1>fatal: the remote end hung up unexpectedly
1>fatal: early EOF
1>fatal: index-pack failed
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/src.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/_gclient_src_OujNcp"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git /Users/user/Desktop/stellite/third_party/chromium_ios/_gclient_src_OujNcp' in '/Users/user/Desktop/stellite/third_party/chromium_ios' attempt 2 / 4
1>Cloning into '/Users/user/Desktop/stellite/third_party/chromium_ios/_gclient_src_OujNcp'...
1>remote: Sending approximately 17.27 GiB ...
1>remote: Counting objects: 224928, done
1>remote: Finding sources: 100% (584/584)
1>remote: Total 13145099 (delta 9913281), reused 13144931 (delta 9913281)
1>Receiving objects: 100% (13145099/13145099), 17.26 GiB | 5.77 MiB/s, done.
1>Resolving deltas: 100% (9913281/9913281), done.

[10:00:10] Still working on:
[10:00:10]   src

[10:00:20] Still working on:
[10:00:20]   src

[10:00:30] Still working on:
[10:00:30]   src

[10:00:40] Still working on:
[10:00:40]   src

[10:00:50] Still working on:
[10:00:50]   src

[10:01:00] Still working on:
[10:01:00]   src

[10:01:10] Still working on:
[10:01:10]   src

[10:01:20] Still working on:
[10:01:20]   src

[10:01:30] Still working on:
[10:01:30]   src

[10:01:40] Still working on:
[10:01:40]   src

[10:01:50] Still working on:
[10:01:50]   src

[10:02:00] Still working on:
[10:02:00]   src

[10:02:10] Still working on:
[10:02:10]   src

[10:02:20] Still working on:
[10:02:20]   src

[10:02:30] Still working on:
[10:02:30]   src

[10:02:40] Still working on:
[10:02:40]   src

[10:02:50] Still working on:
[10:02:50]   src

[10:03:00] Still working on:
[10:03:00]   src

[10:03:10] Still working on:
[10:03:10]   src

[10:03:20] Still working on:
[10:03:20]   src

[10:03:30] Still working on:
[10:03:30]   src

[10:03:40] Still working on:
[10:03:40]   src

[10:03:50] Still working on:
[10:03:50]   src

[10:04:00] Still working on:
[10:04:00]   src

[10:04:10] Still working on:
[10:04:10]   src

[10:04:20] Still working on:
[10:04:20]   src

[10:04:30] Still working on:
[10:04:30]   src

[10:04:40] Still working on:
[10:04:40]   src
1>Syncing projects:   0% ( 0/ 2)
[10:04:49] Still working on:
[10:04:49]   src
Syncing projects:  86% (81/94) src/third_party/angle/third_party/rapidjson/src
[10:54:48] Still working on:
[10:54:48]   src/third_party/catapult
[10:54:48]   src/third_party/icu
[10:54:48]   src/third_party/skia
[10:54:48]   src/third_party/swiftshader
[10:54:48]   src/third_party/webrtc
[10:54:48]   src/v8
[10:54:48]   src/third_party/angle/third_party/deqp/src
[10:54:48]   src/third_party/angle/third_party/vulkan-headers/src

[10:54:58] Still working on:
[10:54:58]   src/third_party/catapult
[10:54:58]   src/third_party/icu
[10:54:58]   src/third_party/skia
[10:54:58]   src/third_party/swiftshader
[10:54:58]   src/third_party/webrtc
[10:54:58]   src/v8
[10:54:58]   src/third_party/angle/third_party/deqp/src
[10:54:58]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:08] Still working on:
[10:55:08]   src/third_party/catapult
[10:55:08]   src/third_party/icu
[10:55:08]   src/third_party/skia
[10:55:08]   src/third_party/swiftshader
[10:55:08]   src/third_party/webrtc
[10:55:08]   src/v8
[10:55:08]   src/third_party/angle/third_party/deqp/src
[10:55:08]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:18] Still working on:
[10:55:18]   src/third_party/catapult
[10:55:18]   src/third_party/icu
[10:55:18]   src/third_party/skia
[10:55:18]   src/third_party/swiftshader
[10:55:18]   src/third_party/webrtc
[10:55:18]   src/v8
[10:55:18]   src/third_party/angle/third_party/deqp/src
[10:55:18]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:28] Still working on:
[10:55:28]   src/third_party/catapult
[10:55:28]   src/third_party/icu
[10:55:28]   src/third_party/skia
[10:55:28]   src/third_party/swiftshader
[10:55:28]   src/third_party/webrtc
[10:55:28]   src/v8
[10:55:28]   src/third_party/angle/third_party/deqp/src
[10:55:28]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:38] Still working on:
[10:55:38]   src/third_party/catapult
[10:55:38]   src/third_party/icu
[10:55:38]   src/third_party/skia
[10:55:38]   src/third_party/swiftshader
[10:55:38]   src/third_party/webrtc
[10:55:38]   src/v8
[10:55:38]   src/third_party/angle/third_party/deqp/src
[10:55:38]   src/third_party/angle/third_party/vulkan-headers/src
89>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Headers" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/angle/third_party/vulkan-headers/_gclient_src_KQ_iCy"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
86>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/deqp" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/angle/third_party/deqp/_gclient_src_ofpur0"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
67>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://skia.googlesource.com/skia.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_skia_1WHkzg"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
20>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/catapult.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_catapult_ualGGy"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
72>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://swiftshader.googlesource.com/SwiftShader.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_swiftshader_MJxEdk"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
85>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/v8/v8.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/_gclient_v8_x3F6S8"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
43>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/icu.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_icu_dAejz3"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...
76>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://webrtc.googlesource.com/src.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_webrtc_PEYZzD"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...

[10:55:48] Still working on:
[10:55:48]   src/third_party/catapult
[10:55:48]   src/third_party/icu
[10:55:48]   src/third_party/skia
[10:55:48]   src/third_party/swiftshader
[10:55:48]   src/third_party/webrtc
[10:55:48]   src/v8
[10:55:48]   src/third_party/angle/third_party/deqp/src
[10:55:48]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:58] Still working on:
[10:55:58]   src/third_party/catapult
[10:55:58]   src/third_party/icu
[10:55:58]   src/third_party/skia
[10:55:58]   src/third_party/swiftshader
[10:55:58]   src/third_party/webrtc
[10:55:58]   src/v8
[10:55:58]   src/third_party/angle/third_party/deqp/src
[10:55:58]   src/third_party/angle/third_party/vulkan-headers/src

[10:55:58] Still working on:
[10:55:58]   src/third_party/catapult
[10:55:58]   src/third_party/icu
[10:55:58]   src/third_party/skia
[10:55:58]   src/third_party/swiftshader
[10:55:58]   src/third_party/webrtc
[10:55:58]   src/v8
[10:55:58]   src/third_party/angle/third_party/deqp/src
[10:55:58]   src/third_party/angle/third_party/vulkan-headers/src
Syncing projects:  87% (82/94) src/third_party/angle/third_party/vulkan-headers/src
[10:56:58] Still working on:
[10:56:58]   src/third_party/catapult
[10:56:58]   src/third_party/icu
[10:56:58]   src/third_party/skia
[10:56:58]   src/third_party/swiftshader
[10:56:58]   src/third_party/webrtc
[10:56:58]   src/v8
[10:56:58]   src/third_party/angle/third_party/deqp/src
[10:56:58]   src/third_party/angle/third_party/vulkan-loader/src

[10:57:08] Still working on:
[10:57:08]   src/third_party/catapult
[10:57:08]   src/third_party/icu
[10:57:08]   src/third_party/skia
[10:57:08]   src/third_party/swiftshader
[10:57:08]   src/third_party/webrtc
[10:57:08]   src/v8
[10:57:08]   src/third_party/angle/third_party/deqp/src
[10:57:08]   src/third_party/angle/third_party/vulkan-loader/src

[10:57:18] Still working on:
[10:57:18]   src/third_party/catapult
[10:57:18]   src/third_party/icu
[10:57:18]   src/third_party/skia
[10:57:18]   src/third_party/swiftshader
[10:57:18]   src/third_party/webrtc
[10:57:18]   src/v8
[10:57:18]   src/third_party/angle/third_party/deqp/src
[10:57:18]   src/third_party/angle/third_party/vulkan-loader/src

[10:57:23] Still working on:
[10:57:23]   src/third_party/catapult
[10:57:23]   src/third_party/icu
[10:57:23]   src/third_party/skia
[10:57:23]   src/third_party/swiftshader
[10:57:23]   src/third_party/webrtc
[10:57:23]   src/v8
[10:57:23]   src/third_party/angle/third_party/deqp/src
[10:57:23]   src/third_party/angle/third_party/vulkan-loader/src
Syncing projects:  93% (88/94) src/third_party/angle/third_party/vulkan-validation-layers/src
[10:59:32] Still working on:
[10:59:32]   src/third_party/catapult
[10:59:32]   src/third_party/icu
[10:59:32]   src/third_party/skia
[10:59:32]   src/third_party/swiftshader
[10:59:32]   src/v8
[10:59:32]   src/third_party/angle/third_party/deqp/src

[10:59:42] Still working on:
[10:59:42]   src/third_party/catapult
[10:59:42]   src/third_party/icu
[10:59:42]   src/third_party/skia
[10:59:42]   src/third_party/swiftshader
[10:59:42]   src/v8
[10:59:42]   src/third_party/angle/third_party/deqp/src

[10:59:47] Still working on:
[10:59:47]   src/third_party/catapult
[10:59:47]   src/third_party/icu
[10:59:47]   src/third_party/skia
[10:59:47]   src/third_party/swiftshader
[10:59:47]   src/v8
[10:59:47]   src/third_party/angle/third_party/deqp/src
Syncing projects:  94% (89/94) src/third_party/swiftshader
[11:00:47] Still working on:
[11:00:47]   src/third_party/catapult
[11:00:47]   src/third_party/icu
[11:00:47]   src/third_party/skia
[11:00:47]   src/v8
[11:00:47]   src/third_party/angle/third_party/deqp/src

[11:00:57] Still working on:
[11:00:57]   src/third_party/catapult
[11:00:57]   src/third_party/icu
[11:00:57]   src/third_party/skia
[11:00:57]   src/v8
[11:00:57]   src/third_party/angle/third_party/deqp/src

[11:01:07] Still working on:
[11:01:07]   src/third_party/catapult
[11:01:07]   src/third_party/icu
[11:01:07]   src/third_party/skia
[11:01:07]   src/v8
[11:01:07]   src/third_party/angle/third_party/deqp/src

[11:01:17] Still working on:
[11:01:17]   src/third_party/catapult
[11:01:17]   src/third_party/icu
[11:01:17]   src/third_party/skia
[11:01:17]   src/v8
[11:01:17]   src/third_party/angle/third_party/deqp/src

[11:01:24] Still working on:
[11:01:24]   src/third_party/catapult
[11:01:24]   src/third_party/icu
[11:01:24]   src/third_party/skia
[11:01:24]   src/v8
[11:01:24]   src/third_party/angle/third_party/deqp/src
Syncing projects:  98% (93/94) src/third_party/angle/third_party/deqp/src
[11:03:49] Still working on:
[11:03:49]   src/third_party/icu

[11:03:59] Still working on:
[11:03:59]   src/third_party/icu

[11:04:09] Still working on:
[11:04:09]   src/third_party/icu

[11:49:49] Still working on:
[11:49:49]   src/third_party/icu

[11:49:59] Still working on:
[11:49:59]   src/third_party/icu

[11:50:09] Still working on:
[11:50:09]   src/third_party/icu

[11:50:19] Still working on:
[11:50:19]   src/third_party/icu

[11:50:29] Still working on:
[11:50:29]   src/third_party/icu

[11:50:39] Still working on:
[11:50:39]   src/third_party/icu
43>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/icu.git" "/Users/user/Desktop/stellite/third_party/chromium_ios/src/third_party/_gclient_icu_dAejz3"' in /Users/user/Desktop/stellite/third_party/chromium_ios failed; will retry after a short nap...

[11:50:49] Still working on:
[11:50:49]   src/third_party/icu

[11:50:59] Still working on:
[11:50:59]   src/third_party/icu

[11:51:09] Still working on:
[11:51:09]   src/third_party/icu

[11:51:19] Still working on:
[11:51:19]   src/third_party/icu

[11:51:29] Still working on:
[11:51:29]   src/third_party/icu

[11:51:39] Still working on:
[11:51:39]   src/third_party/icu

[11:51:49] Still working on:
[11:51:49]   src/third_party/icu

[11:51:59] Still working on:
[11:51:59]   src/third_party/icu

[11:52:09] Still working on:
[11:52:09]   src/third_party/icu

[11:52:19] Still working on:
[11:52:19]   src/third_party/icu

[11:52:29] Still working on:
[11:52:29]   src/third_party/icu

[11:52:39] Still working on:
[11:52:39]   src/third_party/icu

[11:52:49] Still working on:
[11:52:49]   src/third_party/icu

[11:52:59] Still working on:
[11:52:59]   src/third_party/icu

[11:53:09] Still working on:
[11:53:09]   src/third_party/icu

[11:53:19] Still working on:
[11:53:19]   src/third_party/icu

[11:53:29] Still working on:
[11:53:29]   src/third_party/icu

[11:53:39] Still working on:
[11:53:39]   src/third_party/icu

[11:53:49] Still working on:
[11:53:49]   src/third_party/icu

[11:53:59] Still working on:
[11:53:59]   src/third_party/icu

[11:54:09] Still working on:
[11:54:09]   src/third_party/icu

[11:54:19] Still working on:
[11:54:19]   src/third_party/icu

[11:54:29] Still working on:
[11:54:29]   src/third_party/icu

[11:54:39] Still working on:
[11:54:39]   src/third_party/icu

[11:54:49] Still working on:
[11:54:49]   src/third_party/icu

[11:54:58] Still working on:
[11:54:58]   src/third_party/icu
Syncing projects: 100% (94/94), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Running: /Users/user/Desktop/stellite/third_party/depot_tools/gclient sync --jobs 32
Syncing projects: 100% (106/106), done.

WARNING: 'src/third_party/lighttpd' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'src/chrome/installer/mac/third_party/xz/xz' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.
Hook 'vpython src/build/landmines.py' took 173.71 secs
Running hooks:   6% ( 5/79) nacltools
________ running 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' in '/Users/user/Desktop/stellite/third_party/chromium_ios'
INFO: --Syncing nacl_arm_glibc to revision 053185d68ed3b96640f15c4ae457b1ff373c6cac--
INFO: Downloading package archive: binutils_arm_x86_64_apple_darwin.tgz (1/6)
INFO: Downloading package archive: gcc_arm_x86_64_apple_darwin.tgz (2/6)
package_version: Could not download URL (https://storage.googleapis.com/nativeclient-once/object/gcc_arm_x86_64_apple_darwin_8fafa63c02d585ed41994ac603472106f84d584d.tgz): ('The read operation timed out',)
Error: Command 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' returned non-zero exit status 1 in /Users/user/Desktop/stellite/third_party/chromium_ios
Hook 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' took 950.32 secs
Traceback (most recent call last):
  File "./tools/build.py", line 2037, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/build.py", line 2014, in main
    build.fetch_chromium()
  File "./tools/build.py", line 746, in fetch_chromium
    return self.fetch_toolchain()
  File "./tools/build.py", line 1571, in fetch_toolchain
    self.gclient_sync()
  File "./tools/build.py", line 1018, in gclient_sync
    self.execute(command, cwd=self.chromium_path)
  File "./tools/build.py", line 723, in execute
    raise Exception('command execution are failed')
Exception: command execution are failed
AL01166682:stellite user$
```

**Comment by suhchansu** [comment]
Build environment : `XCode8, MacOS High sierra`

**Comment by himansh-gjr** [comment]
Hey @suhchansu I just want to that how you solved this error
I am getting the kind of same error while build [Brave Browser](https://github.com/brave/brave-browser)

TBH new to open source not sure why this error occured

<img width="1440" alt="Screenshot 2021-12-23 at 5 29 17 PM" src="https://user-images.githubusercontent.com/77732259/147237494-23349394-1557-40eb-93e8-7c243dae32a9.png">

My development environment is : `macOS Big sur 11.5.2 , macbook air (with apple chip )`

**Comment by jtyang** [comment]
您好，邮件已经收到，我会尽快回复您！祝您开心...
